CREATE TABLE 受注明細(
     NRJYUTYU     CHAR(7)      NOT NULL,
     SQJYUTYU     SMALLINT     NOT NULL,
     NRHINMOKU    CHAR(7)      NOT NULL,
     PRJYUTYU     DECIMAL(9,2) NOT NULL,
     QTJYUTYU     INTEGER      NOT NULL,
     DTKIBOUNOUKI DATE         NOT NULL,
     QTSYUKKAZUMI INTEGER              ,
CONSTRAINT 受注明細_PK PRIMARY KEY (NRJYUTYU, SQJYUTYU)
);

COMMENT ON COLUMN 受注明細.NRJYUTYU     IS '受注No';
COMMENT ON COLUMN 受注明細.SQJYUTYU     IS '受注行';
COMMENT ON COLUMN 受注明細.NRHINMOKU    IS '受注品目No';
COMMENT ON COLUMN 受注明細.PRJYUTYU     IS '受注単価';
COMMENT ON COLUMN 受注明細.QTJYUTYU     IS '受注数量';
COMMENT ON COLUMN 受注明細.DTKIBOUNOUKI IS '希望納期';
COMMENT ON COLUMN 受注明細.QTSYUKKAZUMI IS '出荷済数量';

ALTER TABLE 受注明細 ADD CONSTRAINT 受注明細_FK1
      FOREIGN KEY (NRJYUTYU)
      REFERENCES 受注見出し (NRJYUTYU);
