CREATE TABLE 受注見出し(
     NRJYUTYU CHAR(7)      NOT NULL,
     DTJYUTYU DATE         NOT NULL,
     TXTEKIYO VARCHAR(300)         ,
CONSTRAINT 受注見出し_PK PRIMARY KEY (NRJYUTYU)
);
COMMENT ON COLUMN 受注見出し.NRJYUTYU IS '受注No';
COMMENT ON COLUMN 受注見出し.DTJYUTYU IS '受注日';
COMMENT ON COLUMN 受注見出し.TXTEKIYO IS '受注摘要';
