CREATE TABLE JTMD(
     NRJYUTYU CHAR(7)      NOT NULL,
     DTJYUTYU DATE         NOT NULL,
     TXTEKIYO VARCHAR(300)         ,
CONSTRAINT JTMD_PK PRIMARY KEY (NRJYUTYU)
);

COMMENT ON TABLE JTMD IS '受注見出し';

COMMENT ON COLUMN JTMD.NRJYUTYU IS '受注No';
COMMENT ON COLUMN JTMD.DTJYUTYU IS '受注日';
COMMENT ON COLUMN JTMD.TXTEKIYO IS '受注摘要';
