CREATE TABLE 品目(
     NRHINMOKU     CHAR(7)                 NOT NULL,
     TXHINBAN      CHAR(15)                NOT NULL,
     TXHINMEI      VARCHAR(40)             NOT NULL,
     KBHINGRP      CHAR(4)                 NOT NULL,
     PRHANBAI      INTEGER     DEFAULT 0   NOT NULL,
     KBZAIKOUM     CHAR(4)     DEFAULT '0' NOT NULL,
     TXTEKIYO      VARCHAR(50)             NOT NULL,
CONSTRAINT 品目_PK PRIMARY KEY (NRHINMOKU),
CONSTRAINT 品目_SK1 UNIQUE (TXHINBAN)
);

COMMENT ON COLUMN 品目.NRHINMOKU IS '内部品目Ｎｏ';
COMMENT ON COLUMN 品目.TXHINBAN  IS '品番';
COMMENT ON COLUMN 品目.TXHINMEI  IS '品名';
COMMENT ON COLUMN 品目.TXHINMEI  IS '品目グループ';
COMMENT ON COLUMN 品目.PRHANBAI  IS '標準売価';
COMMENT ON COLUMN 品目.KBZAIKOUM IS '在庫単位区分';
COMMENT ON COLUMN 品目.TXTEKIYO  IS '仕様摘要';
