CREATE TABLE JTMS(
     NRJYUTYU     CHAR(7)      NOT NULL,
     SQJYUTYU     SMALLINT     NOT NULL,
     NRHINMOKU    CHAR(7)      NOT NULL,
     PRJYUTYU     DECIMAL(9,2) NOT NULL,
     QTJYUTYU     INTEGER      NOT NULL,
     DTKIBOUNOUKI DATE         NOT NULL,
     QTSYUKKAZUMI INTEGER              ,
CONSTRAINT JTMS_PK PRIMARY KEY (NRJYUTYU, SQJYUTYU)
);

COMMENT ON TABLE JTMS IS '受注明細';

COMMENT ON COLUMN JTMS.NRJYUTYU     IS '受注No';
COMMENT ON COLUMN JTMS.SQJYUTYU     IS '受注行';
COMMENT ON COLUMN JTMS.NRHINMOKU    IS '受注品目No';
COMMENT ON COLUMN JTMS.PRJYUTYU     IS '受注単価';
COMMENT ON COLUMN JTMS.QTJYUTYU     IS '受注数量';
COMMENT ON COLUMN JTMS.DTKIBOUNOUKI IS '希望納期';
COMMENT ON COLUMN JTMS.QTSYUKKAZUMI IS '出荷済数量';

ALTER TABLE JTMS ADD CONSTRAINT JTMS_FK1
      FOREIGN KEY (NRJYUTYU)
      REFERENCES JTMD (NRJYUTYU);
