CREATE TABLE HINMOKU(
     NRHINMOKU     CHAR(7)                 NOT NULL,
     TXHINBAN      CHAR(15)                NOT NULL,
     TXHINMEI      VARCHAR(40)             NOT NULL,
     KBHINGRP      CHAR(4)                 NOT NULL,
     PRHANBAI      INTEGER     DEFAULT 0   NOT NULL,
     KBZAIKOUM     CHAR(4)     DEFAULT '0' NOT NULL,
     TXTEKIYO      VARCHAR(50)             NOT NULL,
CONSTRAINT HINMOKU_PK PRIMARY KEY (NRHINMOKU),
CONSTRAINT HINMOKU_SK1 UNIQUE (TXHINBAN)
);

COMMENT ON TABLE HINMOKU IS '品目';

COMMENT ON COLUMN HINMOKU.NRHINMOKU IS '内部品目Ｎｏ';
COMMENT ON COLUMN HINMOKU.TXHINBAN  IS '品番';
COMMENT ON COLUMN HINMOKU.TXHINMEI  IS '品名';
COMMENT ON COLUMN HINMOKU.TXHINMEI  IS '品目グループ';
COMMENT ON COLUMN HINMOKU.PRHANBAI  IS '標準売価';
COMMENT ON COLUMN HINMOKU.KBZAIKOUM IS '在庫単位区分';
COMMENT ON COLUMN HINMOKU.TXTEKIYO  IS '仕様摘要';
